### ISSUE TITLE
[API] Implement Authentication in the backend

### ISSUE THREAD

**Issue by akhilsdeportfolio** [akhilsdeportfolio/visa-app-frontend#2]
**Tasks to complete** 

- [ ] create  Authentication Mechanisim 
- [ ] create Login endpoint
- [ ] create Signup endpoint
